version: "3"
services:
  wp-db:
    image: "postgres"
    environment:
      - POSTGRES_USER=sfn
      - POSTGRES_PASSWORD=sfn
      - POSTGRES_DB=db
    ports:
      - "5433:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
volumes:
  postgres-data: